// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.suite.v1;

import ext.feishu.oapi.core.Config;
import ext.feishu.oapi.core.api.AccessTokenType;
import ext.feishu.oapi.core.api.Api;
import ext.feishu.oapi.core.api.ReqCaller;
import ext.feishu.oapi.core.api.request.Request;
import ext.feishu.oapi.core.api.request.RequestOptFn;
import ext.feishu.oapi.core.api.response.Response;
import ext.feishu.oapi.service.suite.v1.model.DocsApiMetaReqBody;
import ext.feishu.oapi.service.suite.v1.model.DocsApiMetaResult;
import ext.feishu.oapi.service.suite.v1.model.DocsApiSearchReqBody;
import ext.feishu.oapi.service.suite.v1.model.DocsApiSearchResult;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class SuiteService {

    private final Config   config;
    private final DocsApis docsApis;

    public SuiteService(Config config) {
        this.config = config;
        this.docsApis = new DocsApis(this);
    }

    public DocsApis getDocsApis() {
        return docsApis;
    }

    public static class DocsApis {

        private final SuiteService service;

        public DocsApis(SuiteService service) {
            this.service = service;
        }
    
        public DocsApiMetaReqCall meta(DocsApiMetaReqBody body, RequestOptFn... optFns) {
            return new DocsApiMetaReqCall(this, body, optFns);
        }
    
        public DocsApiSearchReqCall search(DocsApiSearchReqBody body, RequestOptFn... optFns) {
            return new DocsApiSearchReqCall(this, body, optFns);
        }
    
    }
    public static class DocsApiMetaReqCall extends ReqCaller<DocsApiMetaReqBody, DocsApiMetaResult> {
        private final DocsApis docsApis;
        
        private final DocsApiMetaReqBody body;
        private final List<RequestOptFn> optFns;
        private DocsApiMetaResult result;
        
        private DocsApiMetaReqCall(DocsApis docsApis, DocsApiMetaReqBody body, RequestOptFn... optFns) {
        
            this.body = body;
            this.optFns = new ArrayList<>();
            this.optFns.addAll(Arrays.asList(optFns));
            this.result = new DocsApiMetaResult();
            this.docsApis = docsApis;
        }
        

        @Override
        public Response<DocsApiMetaResult> execute() throws Exception {
            Request<DocsApiMetaReqBody, DocsApiMetaResult> request = Request.newRequest("/open-apis/suite/docs-api/meta", "POST",
                    new AccessTokenType[]{AccessTokenType.User},
                    this.body, this.result, this.optFns.toArray(new RequestOptFn[]{}));
            return Api.send(this.docsApis.service.config, request);
        }
    }
    public static class DocsApiSearchReqCall extends ReqCaller<DocsApiSearchReqBody, DocsApiSearchResult> {
        private final DocsApis docsApis;
        
        private final DocsApiSearchReqBody body;
        private final List<RequestOptFn> optFns;
        private DocsApiSearchResult result;
        
        private DocsApiSearchReqCall(DocsApis docsApis, DocsApiSearchReqBody body, RequestOptFn... optFns) {
        
            this.body = body;
            this.optFns = new ArrayList<>();
            this.optFns.addAll(Arrays.asList(optFns));
            this.result = new DocsApiSearchResult();
            this.docsApis = docsApis;
        }
        

        @Override
        public Response<DocsApiSearchResult> execute() throws Exception {
            Request<DocsApiSearchReqBody, DocsApiSearchResult> request = Request.newRequest("/open-apis/suite/docs-api/search/object", "POST",
                    new AccessTokenType[]{AccessTokenType.User},
                    this.body, this.result, this.optFns.toArray(new RequestOptFn[]{}));
            return Api.send(this.docsApis.service.config, request);
        }
    }

}
