// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.contact.v3.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class DepartmentCreatedEvent extends BaseEventV2 {
    @SerializedName("event")
    private DepartmentCreatedEventData event;

    public DepartmentCreatedEventData getEvent() {
        return this.event;
    }

    public void setEvent(DepartmentCreatedEventData event) {
        this.event = event;
    }

}
