// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.contact.v3.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class DepartmentDeletedEvent extends BaseEventV2 {
    @SerializedName("event")
    private DepartmentDeletedEventData event;

    public DepartmentDeletedEventData getEvent() {
        return this.event;
    }

    public void setEvent(DepartmentDeletedEventData event) {
        this.event = event;
    }

}
