// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.contact.v3.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class EmployeeTypeEnumDeletedEvent extends BaseEventV2 {
    @SerializedName("event")
    private EmployeeTypeEnumDeletedEventData event;

    public EmployeeTypeEnumDeletedEventData getEvent() {
        return this.event;
    }

    public void setEvent(EmployeeTypeEnumDeletedEventData event) {
        this.event = event;
    }

}
