// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.contact.v3.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class EmployeeTypeEnumDeactivatedEvent extends BaseEventV2 {
    @SerializedName("event")
    private EmployeeTypeEnumDeactivatedEventData event;

    public EmployeeTypeEnumDeactivatedEventData getEvent() {
        return this.event;
    }

    public void setEvent(EmployeeTypeEnumDeactivatedEventData event) {
        this.event = event;
    }

}
