// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.contact.v3.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class EmployeeTypeEnumActivedEvent extends BaseEventV2 {
    @SerializedName("event")
    private EmployeeTypeEnumActivedEventData event;

    public EmployeeTypeEnumActivedEventData getEvent() {
        return this.event;
    }

    public void setEvent(EmployeeTypeEnumActivedEventData event) {
        this.event = event;
    }

}
