// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.contact.v3.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class UserGroupDeletedEvent extends BaseEventV2 {
    @SerializedName("event")
    private UserGroupDeletedEventData event;

    public UserGroupDeletedEventData getEvent() {
        return this.event;
    }

    public void setEvent(UserGroupDeletedEventData event) {
        this.event = event;
    }

}
