// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.contact.v3.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class UserCreatedEvent extends BaseEventV2 {
    @SerializedName("event")
    private UserCreatedEventData event;

    public UserCreatedEventData getEvent() {
        return this.event;
    }

    public void setEvent(UserCreatedEventData event) {
        this.event = event;
    }

}
