// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.contact.v3.model;
import com.google.gson.annotations.SerializedName;

public class UserGroupMemberChangedEventData {
    @SerializedName("object")
    private GroupEvent object;

    public GroupEvent getObject() {
        return this.object;
    }

    public void setObject(GroupEvent object) {
        this.object = object;
    }

}
