// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.face_verify.v1.model;
import com.google.gson.annotations.SerializedName;

public class FaceVerifyUploadFaceImageResult {
    @SerializedName("face_uid")
    private String faceUid;

    public String getFaceUid() {
        return this.faceUid;
    }

    public void setFaceUid(String faceUid) {
        this.faceUid = faceUid;
    }

}
