// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.admin.v1.model;
import com.google.gson.annotations.SerializedName;

public class AuditRecipientDetail {
    @SerializedName("permission_action_type")
    private String permissionActionType;

    public String getPermissionActionType() {
        return this.permissionActionType;
    }

    public void setPermissionActionType(String permissionActionType) {
        this.permissionActionType = permissionActionType;
    }

}
