// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.drive.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class FileReadEvent extends BaseEventV2{
    @SerializedName("event")
    private FileReadEventData event;

    public FileReadEventData getEvent() {
        return this.event;
    }

    public void setEvent(FileReadEventData event) {
        this.event = event;
    }

}
