// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.drive.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class FilePermissionMemberAddedEvent extends BaseEventV2{
    @SerializedName("event")
    private FilePermissionMemberAddedEventData event;

    public FilePermissionMemberAddedEventData getEvent() {
        return this.event;
    }

    public void setEvent(FilePermissionMemberAddedEventData event) {
        this.event = event;
    }

}
