// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.drive.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class FileEditEvent extends BaseEventV2{
    @SerializedName("event")
    private FileEditEventData event;

    public FileEditEventData getEvent() {
        return this.event;
    }

    public void setEvent(FileEditEventData event) {
        this.event = event;
    }

}
