// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.drive.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class FileDeletedEvent extends BaseEventV2{
    @SerializedName("event")
    private FileDeletedEventData event;

    public FileDeletedEventData getEvent() {
        return this.event;
    }

    public void setEvent(FileDeletedEventData event) {
        this.event = event;
    }

}
