// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.drive.v1.model;
import com.google.gson.annotations.SerializedName;

public class ImportTaskGetResult {
    @SerializedName("result")
    private ImportTask result;

    public ImportTask getResult() {
        return this.result;
    }

    public void setResult(ImportTask result) {
        this.result = result;
    }

}
