// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.drive.v1.model;
import com.google.gson.annotations.SerializedName;

public class MediaBatchGetTmpDownloadUrlResult {
    @SerializedName("tmp_download_urls")
    private TmpDownloadUrl[] tmpDownloadUrls;

    public TmpDownloadUrl[] getTmpDownloadUrls() {
        return this.tmpDownloadUrls;
    }

    public void setTmpDownloadUrls(TmpDownloadUrl[] tmpDownloadUrls) {
        this.tmpDownloadUrls = tmpDownloadUrls;
    }

}
