// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.drive.v1.model;
import com.google.gson.annotations.SerializedName;

public class ReplyContent {
    @SerializedName("elements")
    private ReplyElement[] elements;

    public ReplyElement[] getElements() {
        return this.elements;
    }

    public void setElements(ReplyElement[] elements) {
        this.elements = elements;
    }

}
