// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.meeting_room.v1.model;
import com.google.gson.annotations.SerializedName;

public class BuildingCreateResult {
    @SerializedName("building_id")
    private String buildingId;

    public String getBuildingId() {
        return this.buildingId;
    }

    public void setBuildingId(String buildingId) {
        this.buildingId = buildingId;
    }

}
