// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.meeting_room.v1.model;
import com.google.gson.annotations.SerializedName;

public class MeetingRoom {
    @SerializedName("room_id")
    private Integer roomId;

    public Integer getRoomId() {
        return this.roomId;
    }

    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

}
