// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.speech_to_text.v1;

import ext.feishu.oapi.core.Config;
import ext.feishu.oapi.core.api.AccessTokenType;
import ext.feishu.oapi.core.api.Api;
import ext.feishu.oapi.core.api.ReqCaller;
import ext.feishu.oapi.core.api.request.Request;
import ext.feishu.oapi.core.api.request.RequestOptFn;
import ext.feishu.oapi.core.api.response.Response;
import ext.feishu.oapi.service.speech_to_text.v1.model.SpeechFileRecognizeReqBody;
import ext.feishu.oapi.service.speech_to_text.v1.model.SpeechFileRecognizeResult;
import ext.feishu.oapi.service.speech_to_text.v1.model.SpeechStreamRecognizeReqBody;
import ext.feishu.oapi.service.speech_to_text.v1.model.SpeechStreamRecognizeResult;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class SpeechToTextService {

    private final Config  config;
    private final Speechs speechs;

    public SpeechToTextService(Config config) {
        this.config = config;
        this.speechs = new Speechs(this);
    }

    public Speechs getSpeechs() {
        return speechs;
    }

    public static class Speechs {

        private final SpeechToTextService service;

        public Speechs(SpeechToTextService service) {
            this.service = service;
        }
    
        public SpeechFileRecognizeReqCall fileRecognize(SpeechFileRecognizeReqBody body, RequestOptFn... optFns) {
            return new SpeechFileRecognizeReqCall(this, body, optFns);
        }
    
        public SpeechStreamRecognizeReqCall streamRecognize(SpeechStreamRecognizeReqBody body, RequestOptFn... optFns) {
            return new SpeechStreamRecognizeReqCall(this, body, optFns);
        }
    
    }
    public static class SpeechFileRecognizeReqCall extends ReqCaller<SpeechFileRecognizeReqBody, SpeechFileRecognizeResult> {
        private final Speechs speechs;
        
        private final SpeechFileRecognizeReqBody body;
        private final List<RequestOptFn> optFns;
        private SpeechFileRecognizeResult result;
        
        private SpeechFileRecognizeReqCall(Speechs speechs, SpeechFileRecognizeReqBody body, RequestOptFn... optFns) {
        
            this.body = body;
            this.optFns = new ArrayList<>();
            this.optFns.addAll(Arrays.asList(optFns));
            this.result = new SpeechFileRecognizeResult();
            this.speechs = speechs;
        }
        

        @Override
        public Response<SpeechFileRecognizeResult> execute() throws Exception {
            Request<SpeechFileRecognizeReqBody, SpeechFileRecognizeResult> request = Request.newRequest("/open-apis/speech_to_text/v1/speech/file_recognize", "POST",
                    new AccessTokenType[]{AccessTokenType.Tenant},
                    this.body, this.result, this.optFns.toArray(new RequestOptFn[]{}));
            return Api.send(this.speechs.service.config, request);
        }
    }
    public static class SpeechStreamRecognizeReqCall extends ReqCaller<SpeechStreamRecognizeReqBody, SpeechStreamRecognizeResult> {
        private final Speechs speechs;
        
        private final SpeechStreamRecognizeReqBody body;
        private final List<RequestOptFn> optFns;
        private SpeechStreamRecognizeResult result;
        
        private SpeechStreamRecognizeReqCall(Speechs speechs, SpeechStreamRecognizeReqBody body, RequestOptFn... optFns) {
        
            this.body = body;
            this.optFns = new ArrayList<>();
            this.optFns.addAll(Arrays.asList(optFns));
            this.result = new SpeechStreamRecognizeResult();
            this.speechs = speechs;
        }
        

        @Override
        public Response<SpeechStreamRecognizeResult> execute() throws Exception {
            Request<SpeechStreamRecognizeReqBody, SpeechStreamRecognizeResult> request = Request.newRequest("/open-apis/speech_to_text/v1/speech/stream_recognize", "POST",
                    new AccessTokenType[]{AccessTokenType.Tenant},
                    this.body, this.result, this.optFns.toArray(new RequestOptFn[]{}));
            return Api.send(this.speechs.service.config, request);
        }
    }

}
