// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.calendar.v4.model;
import com.google.gson.annotations.SerializedName;

public class CalendarSearchReqBody {
    @SerializedName("query")
    private String query;

    public String getQuery() {
        return this.query;
    }

    public void setQuery(String query) {
        this.query = query;
    }

}
