// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.calendar.v4.model;
import com.google.gson.annotations.SerializedName;

public class CalendarSubscribeResult {
    @SerializedName("calendar")
    private Calendar calendar;

    public Calendar getCalendar() {
        return this.calendar;
    }

    public void setCalendar(Calendar calendar) {
        this.calendar = calendar;
    }

}
