// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.calendar.v4.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class CalendarAclCreatedEvent extends BaseEventV2 {
    @SerializedName("event")
    private CalendarAclCreatedEventData event;

    public CalendarAclCreatedEventData getEvent() {
        return this.event;
    }

    public void setEvent(CalendarAclCreatedEventData event) {
        this.event = event;
    }

}
