// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.calendar.v4.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class CalendarAclDeletedEvent extends BaseEventV2 {
    @SerializedName("event")
    private CalendarAclDeletedEventData event;

    public CalendarAclDeletedEventData getEvent() {
        return this.event;
    }

    public void setEvent(CalendarAclDeletedEventData event) {
        this.event = event;
    }

}
