// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.calendar.v4.model;
import com.google.gson.annotations.SerializedName;

public class SettingGenerateCaldavConfReqBody {
    @SerializedName("device_name")
    private String deviceName;

    public String getDeviceName() {
        return this.deviceName;
    }

    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

}
