// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.application.v1.model;

import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEvent;

public class AppOpenEvent extends BaseEvent {
    @SerializedName("event")
    private AppOpenEventData event;

    public AppOpenEventData getEvent() {
        return this.event;
    }

    public void setEvent(AppOpenEventData event) {
        this.event = event;
    }

}
