// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.application.v1.model;

import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEvent;

public class AppUninstalledEvent extends BaseEvent {
    @SerializedName("event")
    private AppUninstalledEventData event;

    public AppUninstalledEventData getEvent() {
        return this.event;
    }

    public void setEvent(AppUninstalledEventData event) {
        this.event = event;
    }

}
