// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.application.v1.model;

import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEvent;

public class OrderPaidEvent extends BaseEvent {
    @SerializedName("event")
    private OrderPaidEventData event;

    public OrderPaidEventData getEvent() {
        return this.event;
    }

    public void setEvent(OrderPaidEventData event) {
        this.event = event;
    }

}
