// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.sheets.v2.model;
import com.google.gson.annotations.SerializedName;

public class Destination {
    @SerializedName("title")
    private String title;

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
