// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.sheets.v2.model;
import com.google.gson.annotations.SerializedName;

public class SpreadsheetsSheetsBatchUpdateResult {
    @SerializedName("replies")
    private Reply[] replies;

    public Reply[] getReplies() {
        return this.replies;
    }

    public void setReplies(Reply[] replies) {
        this.replies = replies;
    }

}
