// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.sheets.v2.model;
import com.google.gson.annotations.SerializedName;

public class SpreadsheetsValuesPrependReqBody {
    @SerializedName("valueRange")
    private ValueRange valueRange;

    public ValueRange getValueRange() {
        return this.valueRange;
    }

    public void setValueRange(ValueRange valueRange) {
        this.valueRange = valueRange;
    }

}
