// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.sheets.v2.model;
import com.google.gson.annotations.SerializedName;

public class SpreadsheetsStyleUpdateReqBody {
    @SerializedName("appendStyle")
    private AppendStyle appendStyle;

    public AppendStyle getAppendStyle() {
        return this.appendStyle;
    }

    public void setAppendStyle(AppendStyle appendStyle) {
        this.appendStyle = appendStyle;
    }

}
