// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.sheets.v2.model;
import com.google.gson.annotations.SerializedName;

public class SpreadsheetsDimensionRangeAddReqBody {
    @SerializedName("dimension")
    private Dimension dimension;

    public Dimension getDimension() {
        return this.dimension;
    }

    public void setDimension(Dimension dimension) {
        this.dimension = dimension;
    }

}
