// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.sheets.v2.model;
import com.google.gson.annotations.SerializedName;

public class SpreadsheetsImportResult {
    @SerializedName("ticket")
    private String ticket;

    public String getTicket() {
        return this.ticket;
    }

    public void setTicket(String ticket) {
        this.ticket = ticket;
    }

}
