// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.application.v6.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class ApplicationVisibilityAddedEvent extends BaseEventV2 {
    @SerializedName("event")
    private ApplicationVisibilityAddedEventData event;

    public ApplicationVisibilityAddedEventData getEvent() {
        return this.event;
    }

    public void setEvent(ApplicationVisibilityAddedEventData event) {
        this.event = event;
    }

}
