// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.application.v6.model;
import com.google.gson.annotations.SerializedName;

public class UsageUser {
    @SerializedName("user_id")
    private String userId;

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

}
