// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.application.v6.model;
import com.google.gson.annotations.SerializedName;

public class WorkplaceWidget {
    @SerializedName("min_lark_version")
    private String minLarkVersion;

    public String getMinLarkVersion() {
        return this.minLarkVersion;
    }

    public void setMinLarkVersion(String minLarkVersion) {
        this.minLarkVersion = minLarkVersion;
    }

}
