// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.aweme_ecosystem.v1;

import ext.feishu.oapi.core.Config;
import ext.feishu.oapi.core.api.AccessTokenType;
import ext.feishu.oapi.core.api.Api;
import ext.feishu.oapi.core.api.ReqCaller;
import ext.feishu.oapi.core.api.request.Request;
import ext.feishu.oapi.core.api.request.RequestOptFn;
import ext.feishu.oapi.core.api.response.Response;
import ext.feishu.oapi.core.event.Event;
import ext.feishu.oapi.core.event.IHandler;
import ext.feishu.oapi.service.aweme_ecosystem.v1.model.AwemeUserBindedAccountEvent;
import ext.feishu.oapi.service.aweme_ecosystem.v1.model.AwemeUserGetBindInfoResult;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AwemeEcosystemService {

    private final Config     config;
    private final AwemeUsers awemeUsers;

    public AwemeEcosystemService(Config config) {
        this.config = config;
        this.awemeUsers = new AwemeUsers(this);
    }

    public AwemeUsers getAwemeUsers() {
        return awemeUsers;
    }

    public static class AwemeUsers {

        private final AwemeEcosystemService service;

        public AwemeUsers(AwemeEcosystemService service) {
            this.service = service;
        }
    
        public AwemeUserGetBindInfoReqCall getBindInfo(RequestOptFn... optFns) {
            return new AwemeUserGetBindInfoReqCall(this, optFns);
        }
    
    }
    public static class AwemeUserGetBindInfoReqCall extends ReqCaller<Object, AwemeUserGetBindInfoResult> {
        private final AwemeUsers awemeUsers;
        
        private final Map<String, Object> queryParams;
        private final List<RequestOptFn> optFns;
        private AwemeUserGetBindInfoResult result;
        
        private AwemeUserGetBindInfoReqCall(AwemeUsers awemeUsers, RequestOptFn... optFns) {
        
            this.queryParams = new HashMap<>();
            this.optFns = new ArrayList<>();
            this.optFns.addAll(Arrays.asList(optFns));
            this.result = new AwemeUserGetBindInfoResult();
            this.awemeUsers = awemeUsers;
        }
        
        
        public AwemeUserGetBindInfoReqCall setUserIdType(String userIdType){
            this.queryParams.put("user_id_type", userIdType);
            return this;
        }
        public AwemeUserGetBindInfoReqCall setUserId(String userId){
            this.queryParams.put("user_id", userId);
            return this;
        }

        @Override
        public Response<AwemeUserGetBindInfoResult> execute() throws Exception {
            this.optFns.add(Request.setQueryParams(this.queryParams));
            Request<Object, AwemeUserGetBindInfoResult> request = Request.newRequest("/open-apis/aweme_ecosystem/v1/aweme_users/get_bind_info", "POST",
                    new AccessTokenType[]{AccessTokenType.Tenant},
                    null, this.result, this.optFns.toArray(new RequestOptFn[]{}));
            return Api.send(this.awemeUsers.service.config, request);
        }
    }
    public void setAwemeUserBindedAccountEventHandler(AwemeUserBindedAccountEventHandler handler) {
        Event.setTypeHandler(this.config, "aweme_ecosystem.aweme_user.binded_account_v1", handler);
    }

    public abstract static class AwemeUserBindedAccountEventHandler implements IHandler<AwemeUserBindedAccountEvent> {
        @Override
        public AwemeUserBindedAccountEvent getEvent() {
            return new AwemeUserBindedAccountEvent();
        }
    }

}
