// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.tenant.v2;

import ext.feishu.oapi.core.Config;
import ext.feishu.oapi.core.api.AccessTokenType;
import ext.feishu.oapi.core.api.Api;
import ext.feishu.oapi.core.api.ReqCaller;
import ext.feishu.oapi.core.api.request.Request;
import ext.feishu.oapi.core.api.request.RequestOptFn;
import ext.feishu.oapi.core.api.response.Response;
import ext.feishu.oapi.service.tenant.v2.model.TenantQueryResult;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class TenantService {

    private final Config  config;
    private final Tenants tenants;

    public TenantService(Config config) {
        this.config = config;
        this.tenants = new Tenants(this);
    }

    public Tenants getTenants() {
        return tenants;
    }

    public static class Tenants {

        private final TenantService service;

        public Tenants(TenantService service) {
            this.service = service;
        }
    
        public TenantQueryReqCall query(RequestOptFn... optFns) {
            return new TenantQueryReqCall(this, optFns);
        }
    
    }
    public static class TenantQueryReqCall extends ReqCaller<Object, TenantQueryResult> {
        private final Tenants tenants;
        
        private final List<RequestOptFn> optFns;
        private TenantQueryResult result;
        
        private TenantQueryReqCall(Tenants tenants, RequestOptFn... optFns) {
        
            this.optFns = new ArrayList<>();
            this.optFns.addAll(Arrays.asList(optFns));
            this.result = new TenantQueryResult();
            this.tenants = tenants;
        }
        

        @Override
        public Response<TenantQueryResult> execute() throws Exception {
            Request<Object, TenantQueryResult> request = Request.newRequest("/open-apis/tenant/v2/tenant/query", "GET",
                    new AccessTokenType[]{AccessTokenType.Tenant},
                    null, this.result, this.optFns.toArray(new RequestOptFn[]{}));
            return Api.send(this.tenants.service.config, request);
        }
    }

}
