// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.bitable.v1.model;
import com.google.gson.annotations.SerializedName;

public class AppTableFieldCreateResult {
    @SerializedName("field")
    private AppTableField field;

    public AppTableField getField() {
        return this.field;
    }

    public void setField(AppTableField field) {
        this.field = field;
    }

}
