// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.bitable.v1.model;
import com.google.gson.annotations.SerializedName;

public class AppTableCreateResult {
    @SerializedName("table_id")
    private String tableId;

    public String getTableId() {
        return this.tableId;
    }

    public void setTableId(String tableId) {
        this.tableId = tableId;
    }

}
