// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.bitable.v1.model;
import com.google.gson.annotations.SerializedName;

public class AppTableRecordGetResult {
    @SerializedName("record")
    private AppTableRecord record;

    public AppTableRecord getRecord() {
        return this.record;
    }

    public void setRecord(AppTableRecord record) {
        this.record = record;
    }

}
