// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.bitable.v1.model;
import com.google.gson.annotations.SerializedName;

public class AppTableViewCreateResult {
    @SerializedName("app.table.view")
    private AppTableView appTableView;

    public AppTableView getAppTableView() {
        return this.appTableView;
    }

    public void setAppTableView(AppTableView appTableView) {
        this.appTableView = appTableView;
    }

}
