// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.bitable.v1.model;
import com.google.gson.annotations.SerializedName;

public class AppTableBatchCreateReqBody {
    @SerializedName("tables")
    private ReqTable[] tables;

    public ReqTable[] getTables() {
        return this.tables;
    }

    public void setTables(ReqTable[] tables) {
        this.tables = tables;
    }

}
