// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.bitable.v1.model;
import com.google.gson.annotations.SerializedName;

public class Option {
    @SerializedName("name")
    private String name;

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
