// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.drive_explorer.v2.model;
import com.google.gson.annotations.SerializedName;

public class FolderCreateReqBody {
    @SerializedName("title")
    private String title;

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
