// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.doc.v2.model;
import com.google.gson.annotations.SerializedName;

public class DocRawContentResult {
    @SerializedName("content")
    private String content;

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
