// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.docx.v1.model;
import com.google.gson.annotations.SerializedName;

public class DocumentBlockGetResult {
    @SerializedName("block")
    private Block block;

    public Block getBlock() {
        return this.block;
    }

    public void setBlock(Block block) {
        this.block = block;
    }

}
