// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.docx.v1.model;
import com.google.gson.annotations.SerializedName;

public class GridColumn {
    @SerializedName("width_ratio")
    private Integer widthRatio;

    public Integer getWidthRatio() {
        return this.widthRatio;
    }

    public void setWidthRatio(Integer widthRatio) {
        this.widthRatio = widthRatio;
    }

}
