// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.docx.v1.model;
import com.google.gson.annotations.SerializedName;

public class Iframe {
    @SerializedName("component")
    private IframeComponent component;

    public IframeComponent getComponent() {
        return this.component;
    }

    public void setComponent(IframeComponent component) {
        this.component = component;
    }

}
