// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.docx.v1.model;
import com.google.gson.annotations.SerializedName;

public class InlineBlock {
    @SerializedName("block_id")
    private String blockId;

    public String getBlockId() {
        return this.blockId;
    }

    public void setBlockId(String blockId) {
        this.blockId = blockId;
    }

}
