// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.docx.v1.model;
import com.google.gson.annotations.SerializedName;

public class InsertGridColumnRequest {
    @SerializedName("column_index")
    private Integer columnIndex;

    public Integer getColumnIndex() {
        return this.columnIndex;
    }

    public void setColumnIndex(Integer columnIndex) {
        this.columnIndex = columnIndex;
    }

}
