// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.docx.v1.model;
import com.google.gson.annotations.SerializedName;

public class UpdateGridColumnWidthRatioRequest {
    @SerializedName("width_ratios")
    private Integer[] widthRatios;

    public Integer[] getWidthRatios() {
        return this.widthRatios;
    }

    public void setWidthRatios(Integer[] widthRatios) {
        this.widthRatios = widthRatios;
    }

}
