// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.task.v1.model;
import com.google.gson.annotations.SerializedName;

public class Follower {
    @SerializedName("id")
    private String id;

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

}
