// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.task.v1.model;
import com.google.gson.annotations.SerializedName;

public class TaskReminderCreateResult {
    @SerializedName("reminder")
    private Reminder reminder;

    public Reminder getReminder() {
        return this.reminder;
    }

    public void setReminder(Reminder reminder) {
        this.reminder = reminder;
    }

}
