// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.task.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class TaskCommentUpdatedEvent extends BaseEventV2{
    @SerializedName("event")
    private TaskCommentUpdatedEventData event;

    public TaskCommentUpdatedEventData getEvent() {
        return this.event;
    }

    public void setEvent(TaskCommentUpdatedEventData event) {
        this.event = event;
    }

}
