// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.task.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class TaskUpdatedEvent extends BaseEventV2{
    @SerializedName("event")
    private TaskUpdatedEventData event;

    public TaskUpdatedEventData getEvent() {
        return this.event;
    }

    public void setEvent(TaskUpdatedEventData event) {
        this.event = event;
    }

}
