// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.search.v2.model;
import com.google.gson.annotations.SerializedName;

public class DataSourcePatchResult {
    @SerializedName("data_source")
    private DataSource dataSource;

    public DataSource getDataSource() {
        return this.dataSource;
    }

    public void setDataSource(DataSource dataSource) {
        this.dataSource = dataSource;
    }

}
