// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.search.v2.model;
import com.google.gson.annotations.SerializedName;

public class ItemContent {
    @SerializedName("format")
    private String format;
    @SerializedName("content_data")
    private String contentData;

    public String getFormat() {
        return this.format;
    }

    public void setFormat(String format) {
        this.format = format;
    }

    public String getContentData() {
        return this.contentData;
    }

    public void setContentData(String contentData) {
        this.contentData = contentData;
    }

}
