// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.acs.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class AccessRecordCreatedEvent extends BaseEventV2{
    @SerializedName("event")
    private AccessRecordCreatedEventData event;

    public AccessRecordCreatedEventData getEvent() {
        return this.event;
    }

    public void setEvent(AccessRecordCreatedEventData event) {
        this.event = event;
    }

}
