// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.acs.v1.model;
import com.google.gson.annotations.SerializedName;

public class UserGetResult {
    @SerializedName("user")
    private User user;

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

}
