// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.acs.v1.model;
import com.google.gson.annotations.SerializedName;

public class User {
    @SerializedName("feature")
    private Feature feature;
    @SerializedName("user_id")
    private String userId;

    public Feature getFeature() {
        return this.feature;
    }

    public void setFeature(Feature feature) {
        this.feature = feature;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

}
