// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.acs.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class UserUpdatedEvent extends BaseEventV2{
    @SerializedName("event")
    private UserUpdatedEventData event;

    public UserUpdatedEventData getEvent() {
        return this.event;
    }

    public void setEvent(UserUpdatedEventData event) {
        this.event = event;
    }

}
