// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.aweme_ecosystem.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class AwemeUserBindedAccountEvent extends BaseEventV2 {
    @SerializedName("event")
    private AwemeUserBindedAccountEventData event;

    public AwemeUserBindedAccountEventData getEvent() {
        return this.event;
    }

    public void setEvent(AwemeUserBindedAccountEventData event) {
        this.event = event;
    }

}
