// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.drive_permission.v2;

import ext.feishu.oapi.core.Config;
import ext.feishu.oapi.core.api.AccessTokenType;
import ext.feishu.oapi.core.api.Api;
import ext.feishu.oapi.core.api.ReqCaller;
import ext.feishu.oapi.core.api.request.Request;
import ext.feishu.oapi.core.api.request.RequestOptFn;
import ext.feishu.oapi.core.api.response.EmptyData;
import ext.feishu.oapi.core.api.response.Response;
import ext.feishu.oapi.service.drive_permission.v2.model.PublicGetReqBody;
import ext.feishu.oapi.service.drive_permission.v2.model.PublicGetResult;
import ext.feishu.oapi.service.drive_permission.v2.model.PublicUpdateReqBody;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class DrivePermissionService {

    private final Config  config;
    private final Publics publics;

    public DrivePermissionService(Config config) {
        this.config = config;
        this.publics = new Publics(this);
    }

    public Publics getPublics() {
        return publics;
    }

    public static class Publics {

        private final DrivePermissionService service;

        public Publics(DrivePermissionService service) {
            this.service = service;
        }
    
        public PublicGetReqCall get(PublicGetReqBody body, RequestOptFn... optFns) {
            return new PublicGetReqCall(this, body, optFns);
        }
    
        public PublicUpdateReqCall update(PublicUpdateReqBody body, RequestOptFn... optFns) {
            return new PublicUpdateReqCall(this, body, optFns);
        }
    
    }
    public static class PublicGetReqCall extends ReqCaller<PublicGetReqBody, PublicGetResult> {
        private final Publics publics;
        
        private final PublicGetReqBody body;
        private final List<RequestOptFn> optFns;
        private PublicGetResult result;
        
        private PublicGetReqCall(Publics publics, PublicGetReqBody body, RequestOptFn... optFns) {
        
            this.body = body;
            this.optFns = new ArrayList<>();
            this.optFns.addAll(Arrays.asList(optFns));
            this.result = new PublicGetResult();
            this.publics = publics;
        }
        

        @Override
        public Response<PublicGetResult> execute() throws Exception {
            Request<PublicGetReqBody, PublicGetResult> request = Request.newRequest("/open-apis/drive/permission/v2/public", "POST",
                    new AccessTokenType[]{AccessTokenType.User, AccessTokenType.Tenant},
                    this.body, this.result, this.optFns.toArray(new RequestOptFn[]{}));
            return Api.send(this.publics.service.config, request);
        }
    }
    public static class PublicUpdateReqCall extends ReqCaller<PublicUpdateReqBody, EmptyData> {
        private final Publics publics;
        
        private final PublicUpdateReqBody body;
        private final List<RequestOptFn> optFns;
        private EmptyData result;
        
        private PublicUpdateReqCall(Publics publics, PublicUpdateReqBody body, RequestOptFn... optFns) {
        
            this.body = body;
            this.optFns = new ArrayList<>();
            this.optFns.addAll(Arrays.asList(optFns));
            this.result = new EmptyData();
            this.publics = publics;
        }
        

        @Override
        public Response<EmptyData> execute() throws Exception {
            Request<PublicUpdateReqBody, EmptyData> request = Request.newRequest("/open-apis/drive/permission/v2/public/update", "POST",
                    new AccessTokenType[]{AccessTokenType.User, AccessTokenType.Tenant},
                    this.body, this.result, this.optFns.toArray(new RequestOptFn[]{}));
            return Api.send(this.publics.service.config, request);
        }
    }

}
