// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.vc.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class MeetingJoinMeetingEvent extends BaseEventV2{
    @SerializedName("event")
    private MeetingJoinMeetingEventData event;

    public MeetingJoinMeetingEventData getEvent() {
        return this.event;
    }

    public void setEvent(MeetingJoinMeetingEventData event) {
        this.event = event;
    }

}
