// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.vc.v1.model;
import com.google.gson.annotations.SerializedName;

public class MeetingRecordingSetPermissionReqBody {
    @SerializedName("permission_objects")
    private RecordingPermissionObject[] permissionObjects;

    public RecordingPermissionObject[] getPermissionObjects() {
        return this.permissionObjects;
    }

    public void setPermissionObjects(RecordingPermissionObject[] permissionObjects) {
        this.permissionObjects = permissionObjects;
    }

}
