// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.vc.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class MeetingMeetingStartedEvent extends BaseEventV2{
    @SerializedName("event")
    private MeetingMeetingStartedEventData event;

    public MeetingMeetingStartedEventData getEvent() {
        return this.event;
    }

    public void setEvent(MeetingMeetingStartedEventData event) {
        this.event = event;
    }

}
