// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.vc.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class MeetingShareEndedEvent extends BaseEventV2{
    @SerializedName("event")
    private MeetingShareEndedEventData event;

    public MeetingShareEndedEventData getEvent() {
        return this.event;
    }

    public void setEvent(MeetingShareEndedEventData event) {
        this.event = event;
    }

}
