// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.vc.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class MeetingRecordingStartedEvent extends BaseEventV2{
    @SerializedName("event")
    private MeetingRecordingStartedEventData event;

    public MeetingRecordingStartedEventData getEvent() {
        return this.event;
    }

    public void setEvent(MeetingRecordingStartedEventData event) {
        this.event = event;
    }

}
