// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.vc.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class MeetingRecordingEndedEvent extends BaseEventV2{
    @SerializedName("event")
    private MeetingRecordingEndedEventData event;

    public MeetingRecordingEndedEventData getEvent() {
        return this.event;
    }

    public void setEvent(MeetingRecordingEndedEventData event) {
        this.event = event;
    }

}
