// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.vc.v1.model;
import com.google.gson.annotations.SerializedName;

public class ReserveCallSetting {
    @SerializedName("callee")
    private ReserveCallee callee;

    public ReserveCallee getCallee() {
        return this.callee;
    }

    public void setCallee(ReserveCallee callee) {
        this.callee = callee;
    }

}
