// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.drive_permission.v1.model;
import com.google.gson.annotations.SerializedName;

public class MemberListResult {
    @SerializedName("members")
    private Collaborator[] members;

    public Collaborator[] getMembers() {
        return this.members;
    }

    public void setMembers(Collaborator[] members) {
        this.members = members;
    }

}
