// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.drive_permission.v1.model;
import com.google.gson.annotations.SerializedName;

public class MemberPermittedResult {
    @SerializedName("is_permitted")
    private Boolean isPermitted;

    public Boolean getIsPermitted() {
        return this.isPermitted;
    }

    public void setIsPermitted(Boolean isPermitted) {
        this.isPermitted = isPermitted;
    }

}
