// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.im.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class ChatUpdatedEvent extends BaseEventV2{
    @SerializedName("event")
    private ChatUpdatedEventData event;

    public ChatUpdatedEventData getEvent() {
        return this.event;
    }

    public void setEvent(ChatUpdatedEventData event) {
        this.event = event;
    }

}
