// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.im.v1.model;
import com.google.gson.annotations.SerializedName;

public class MembersDeleteReqBody {
    @SerializedName("id_list")
    private String[] idList;

    public String[] getIdList() {
        return this.idList;
    }

    public void setIdList(String[] idList) {
        this.idList = idList;
    }

}
