// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.im.v1.model;
import com.google.gson.annotations.SerializedName;

public class MembersIsInChatResult {
    @SerializedName("is_in_chat")
    private Boolean isInChat;

    public Boolean getIsInChat() {
        return this.isInChat;
    }

    public void setIsInChat(Boolean isInChat) {
        this.isInChat = isInChat;
    }

}
