// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.im.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class MessageReceiveEvent extends BaseEventV2{
    @SerializedName("event")
    private MessageReceiveEventData event;

    public MessageReceiveEventData getEvent() {
        return this.event;
    }

    public void setEvent(MessageReceiveEventData event) {
        this.event = event;
    }

}
