// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.im.v1.model;
import com.google.gson.annotations.SerializedName;
import ext.feishu.oapi.core.event.model.BaseEventV2;

public class MessageAtMessageReadEvent extends BaseEventV2{
    @SerializedName("event")
    private MessageAtMessageReadEventData event;

    public MessageAtMessageReadEventData getEvent() {
        return this.event;
    }

    public void setEvent(MessageAtMessageReadEventData event) {
        this.event = event;
    }

}
