// Code generated by lark suite oapi sdk gen
package ext.feishu.oapi.service.im.v1.model;
import com.google.gson.annotations.SerializedName;

public class MessageGetResult {
    @SerializedName("items")
    private Message[] items;

    public Message[] getItems() {
        return this.items;
    }

    public void setItems(Message[] items) {
        this.items = items;
    }

}
